version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
#       - "echo Logging in to Docker Hub..."
#       - "docker login --username=\"dvohra\" --password=\"password\""
  build:
    commands:
      - echo Build started on 'date'
      - mvn clean package --quiet
#       - "echo Building the Docker image..."
#       - "docker build -t dvohra/node-server ."
#       - "docker tag dvohra/node-server dvohra/node-server:latest"
  post_build:
    commands:
      - echo Build completed on 'date'
#       - "echo Pushing the Docker image..."
#       - "docker push dvohra/node-server:latest"
artifacts:
  discard-paths: yes
  files:
    - target/*
#     -scripts/*
#     -appspec/*
    
